site_name: Waffles
site_url: 'https://waffles.terrarum.net'
site_description: 'A simple configuration management system written in Bash'
site_dir: 'mkdocs-site'
repo_url: 'https://github.com/jtopjian/waffles'
theme: 'readthedocs'

pages:
  - Home: 'index.md'
  - About: 'about.md'
  - Quickstart: 'quickstart.md'
  - Installation: 'cookbook/install.md'
  - Concepts: 'concepts.md'
  - Usage: 'usage.md'
  - Modules: 'modules.md'
  - Functions:
    - 'Types': 'functions/types.md'
    - 'system': 'functions/system.md'
    - 'catalog': 'functions/catalog.md'
    - 'options': 'functions/options.md'
    - 'augeas': 'functions/augeas.md'
    - 'mysql': 'functions/mysql.md'
  - Cookbook:
    - 'Environment Variables': 'cookbook/environment-vars.md'
    - 'Deploying a MySQL Server': 'cookbook/deploying-a-mysql-server.md'
    - 'Deploying a MySQL Galera Cluster': 'cookbook/deploying-a-mysql-galera-cluster.md'
    - 'Deploying a Consul Cluster': 'cookbook/deploying-a-consul-cluster.md'
    - 'Overriding Data': 'cookbook/override-data.md'
    - 'Referencing Data from Data': 'cookbook/referencing-data-from-data.md'
    - 'Testing Waffles with Test Kitchen': 'cookbook/testing-with-test-kitchen.md'
    - 'Waffles and LXC': 'cookbook/waffles-and-lxc.md'
    - 'Waffles and Terraform': 'cookbook/waffles-and-terraform.md'
  - Resources:
    - Internals: 'resources.md'
    - stdlib.apt_key: 'resources/stdlib.apt_key.md'
    - stdlib.apt_ppa: 'resources/stdlib.apt_ppa.md'
    - stdlib.apt: 'resources/stdlib.apt.md'
    - stdlib.apt_source: 'resources/stdlib.apt_source.md'
    - stdlib.cron: 'resources/stdlib.cron.md'
    - stdlib.debconf: 'resources/stdlib.debconf.md'
    - stdlib.directory: 'resources/stdlib.directory.md'
    - stdlib.file_line: 'resources/stdlib.file_line.md'
    - stdlib.file: 'resources/stdlib.file.md'
    - stdlib.git: 'resources/stdlib.git.md'
    - stdlib.groupadd: 'resources/stdlib.groupadd.md'
    - stdlib.ini: 'resources/stdlib.ini.md'
    - stdlib.ip6tables_rule: 'resources/stdlib.ip6tables_rule.md'
    - stdlib.iptables_rule: 'resources/stdlib.iptables_rule.md'
    - stdlib.sysvinit: 'resources/stdlib.sysvinit.md'
    - stdlib.upstart: 'resources/stdlib.upstart.md'
    - stdlib.useradd: 'resources/stdlib.useradd.md'
    - augeas.aptconf: 'resources/augeas.aptconf.md'
    - augeas.cron: 'resources/augeas.cron.md'
    - augeas.file_line: 'resources/augeas.file_line.md'
    - augeas.host: 'resources/augeas.host.md'
    - augeas.ini: 'resources/augeas.ini.md'
    - augeas.json_array: 'resources/augeas.json_array.md'
    - augeas.json_dict: 'resources/augeas.json_dict.md'
    - augeas.mail_alias: 'resources/augeas.mail_alias.md'
    - augeas.shellvar: 'resources/augeas.shellvar.md'
    - augeas.ssh_authorized_key: 'resources/augeas.ssh_authorized_key.md'
    - mysql.database: 'resources/mysql.database.md'
    - mysql.grant: 'resources/mysql.grant.md'
    - mysql.user: 'resources/mysql.user.md'
    - rabbitmq.policy: 'resources/rabbitmq.policy.md'
    - rabbitmq.user_permissions: 'resources/rabbitmq.user_permissions.md'
    - rabbitmq.user: 'resources/rabbitmq.user.md'
    - rabbitmq.vhost: 'resources/rabbitmq.vhost.md'
