site_name: Waffles
site_url: 'https://waffles.terrarum.net'
site_description: 'A simple configuration management system written in Bash'
site_dir: 'mkdocs-site'
repo_url: 'https://github.com/jtopjian/waffles'
theme: 'readthedocs'

pages:
  - Home: 'index.md'
  - About: 'about.md'
  - Quickstart: 'quickstart.md'
  - Installation: 'cookbook/install.md'
  - Concepts: 'concepts.md'
  - Usage: 'usage.md'
  - Modules: 'modules.md'
  - Functions:
    - 'Types': 'functions/types.md'
    - 'system': 'functions/system.md'
    - 'catalog': 'functions/catalog.md'
    - 'options': 'functions/options.md'
    - 'augeas': 'functions/augeas.md'
    - 'mysql': 'functions/mysql.md'
  - Cookbook:
    - 'Environment Variables': 'cookbook/environment-vars.md'
    - 'Deploying a MySQL Server': 'cookbook/deploying-a-mysql-server.md'
    - 'Deploying a MySQL Galera Cluster': 'cookbook/deploying-a-mysql-galera-cluster.md'
    - 'Deploying a Consul Cluster': 'cookbook/deploying-a-consul-cluster.md'
    - 'Overriding Data': 'cookbook/override-data.md'
    - 'Referencing Data from Data': 'cookbook/referencing-data-from-data.md'
    - 'Testing Waffles with Test Kitchen': 'cookbook/testing-with-test-kitchen.md'
    - 'Waffles and LXC': 'cookbook/waffles-and-lxc.md'
    - 'Waffles and Terraform': 'cookbook/waffles-and-terraform.md'
  - Resources:
    - Internals: 'resources.md'
    - stdlib.apt_key: 'resources/stdlib.apt_key.md'
    - stdlib.apt_ppa: 'resources/stdlib.apt_ppa.md'
    - stdlib.apt: 'resources/stdlib.apt.md'
    - stdlib.apt_source: 'resources/stdlib.apt_source.md'
    - stdlib.cron: 'resources/stdlib.cron.md'
    - stdlib.debconf: 'resources/stdlib.debconf.md'
    - stdlib.directory: 'resources/stdlib.directory.md'
    - stdlib.file_line: 'resources/stdlib.file_line.md'
    - stdlib.file: 'resources/stdlib.file.md'
    - stdlib.git: 'resources/stdlib.git.md'
    - stdlib.groupadd: 'resources/stdlib.groupadd.md'
    - stdlib.ini: 'resources/stdlib.ini.md'
    - stdlib.ip6tables_rule: 'resources/stdlib.ip6tables_rule.md'
    - stdlib.iptables_rule: 'resources/stdlib.iptables_rule.md'
    - stdlib.sysvinit: 'resources/stdlib.sysvinit.md'
    - stdlib.upstart: 'resources/stdlib.upstart.md'
    - stdlib.useradd: 'resources/stdlib.useradd.md'
    - apache.section: 'resources/apache.section.md'
    - apache.setting: 'resources/apache.setting.md'
    - augeas.aptconf: 'resources/augeas.aptconf.md'
    - augeas.cron: 'resources/augeas.cron.md'
    - augeas.file_line: 'resources/augeas.file_line.md'
    - augeas.host: 'resources/augeas.host.md'
    - augeas.ini: 'resources/augeas.ini.md'
    - augeas.json_array: 'resources/augeas.json_array.md'
    - augeas.json_dict: 'resources/augeas.json_dict.md'
    - augeas.mail_alias: 'resources/augeas.mail_alias.md'
    - augeas.shellvar: 'resources/augeas.shellvar.md'
    - augeas.ssh_authorized_key: 'resources/augeas.ssh_authorized_key.md'
    - mysql.database: 'resources/mysql.database.md'
    - mysql.grant: 'resources/mysql.grant.md'
    - mysql.user: 'resources/mysql.user.md'
    - nginx.events: 'resources/nginx.events.md'
    - nginx.global: 'resources/nginx.global.md'
    - nginx.http: 'resources/nginx.http.md'
    - nginx.if: 'resources/nginx.if.md'
    - nginx.location: 'resources/nginx.location.md'
    - nginx.map: 'resources/nginx.map.md'
    - nginx.server: 'resources/nginx.server.md'
    - nginx.upstream: 'resources/nginx.upstream.md'
    - rabbitmq.auth_backend: 'resources/rabbitmq.auth_backend.md'
    - rabbitmq.auth_mechanism: 'resources/rabbitmq.auth_mechanism.md'
    - rabbitmq.backing_queue_module: 'resources/rabbitmq.backing_queue_module.md'
    - rabbitmq.cluster_nodes: 'resources/rabbitmq.cluster_nodes.md'
    - rabbitmq.collect_statistics_interval: 'resources/rabbitmq.collect_statistics_interval.md'
    - rabbitmq.collect_statistics: 'resources/rabbitmq.collect_statistics.md'
    - rabbitmq.default_permissions: 'resources/rabbitmq.default_permissions.md'
    - rabbitmq.default_user: 'resources/rabbitmq.default_user.md'
    - rabbitmq.default_user_tags: 'resources/rabbitmq.default_user_tags.md'
    - rabbitmq.default_vhost: 'resources/rabbitmq.default_vhost.md'
    - rabbitmq.delegate_count: 'resources/rabbitmq.delegate_count.md'
    - rabbitmq.disk_free_limit: 'resources/rabbitmq.disk_free_limit.md'
    - rabbitmq.frame_max: 'resources/rabbitmq.frame_max.md'
    - rabbitmq.heartbeat: 'resources/rabbitmq.heartbeat.md'
    - rabbitmq.hipe_compile: 'resources/rabbitmq.hipe_compile.md'
    - rabbitmq.log_levels: 'resources/rabbitmq.log_levels.md'
    - rabbitmq.msg_store_file_size_limit: 'resources/rabbitmq.msg_store_file_size_limit.md'
    - rabbitmq.msg_store_index_module: 'resources/rabbitmq.msg_store_index_module.md'
    - rabbitmq.policy: 'resources/rabbitmq.policy.md'
    - rabbitmq.queue_index_max_journal_entries: 'resources/rabbitmq.queue_index_max_journal_entries.md'
    - rabbitmq.ssl_listeners: 'resources/rabbitmq.ssl_listeners.md'
    - rabbitmq.ssl_options: 'resources/rabbitmq.ssl_options.md'
    - rabbitmq.tcp_listeners: 'resources/rabbitmq.tcp_listeners.md'
    - rabbitmq.user_permissions: 'resources/rabbitmq.user_permissions.md'
    - rabbitmq.user: 'resources/rabbitmq.user.md'
    - rabbitmq.vhost: 'resources/rabbitmq.vhost.md'
    - rabbitmq.vm_memory_high_watermark: 'resources/rabbitmq.vm_memory_high_watermark.md'
